apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/alertmanager/metrics'
  labels:
    name: alertmanager
  name: alertmanager
  namespace: monitoring
spec:
  selector:
    app: alertmanager
  ports:
  - name: alertmanager
    protocol: TCP
    port: 9093
    targetPort: 9093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.8.0
        env:
        - name: SLACK_HOOK_URL
          value: "<slack url here>"
        command: ['/bin/sh', '/etc/alertmanager/configure_secret.sh']
        args:
          - '-config.file=/etc/alertmanager/config.yml'
          - '-storage.path=/alertmanager'
        ports:
        - name: alertmanager
          containerPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager
      nodeSelector:
        beta.kubernetes.io/os: linux
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: monitoring
data:
  config.yml: |-
    global:
      slack_api_url: https://hooks.slack.com/services/API_URL_SECRET

    route:
      group_by: [cluster]
      # If an alert isn't caught by a route, send it to slack.
      receiver: slack-all
      routes:
        - match:
            severity: slack
          receiver: slack-all


    receivers:
    - name: 'slack-all'
      slack_configs:
      - channel: '#sockshop-ops'
        send_resolved: true
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        api_url: https://hooks.slack.com/services/API_URL_SECRET
  configure_secret.sh: |-
    echo 'Configuring Slack hook url.'
    sed -i -e s,API_URL_SECRET,"$SLACK_HOOK_URL",g /etc/alertmanager/config.yml
    exec /bin/alertmanager $*
