---
kind: Pod
apiVersion: v1
metadata:
  name: k8s-counter
  labels:
    name: my-example-pod
spec:
  containers:
  - name: my-container
    image: gcr.io/jetstack-workshops/k8s-counter
    ports:
    - containerPort: 80
      protocol: TCP
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "highCpu"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: dedicated
            operator: In
            values:
            - highCpu
