apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: sock-shop
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: <your.host.here>
    http:
      paths:
      - path: /
        backend:
          serviceName: front-end
          servicePort: 80
